### PR TITLE
make console depend on all graphds

### PR DESCRIPTION
**Pull request by wey-gu**
close: #126

credit goes to @imrefazekas

### CODE REVIEW

**Comment by wey-gu** [comment]
As observed by @imrefazekas it took some time for the cluster to be ready to receive the console call, this change helped fix it.

**Comment by HarrisChu** [comment]
why this? console just connect to `FIRST` graph, no need to wait other graphds.
prefer a loop like: https://github.com/vesoft-inc/nebula-python/blob/master/tests/docker-compose.yaml

**Comment by HarrisChu** [comment]
```
        for i in `seq 1 60`;do
          var=`nebula-console -addr graphd0 -port 9669 -u root -p nebula -e 'ADD HOSTS "172.28.2.1":9779,"172.28.2.2":9779,"172.28.2.3":9779;'`;
          if [[ $$? == 0 ]];then
            break;
          fi;
          sleep 1;
          echo "retry to add hosts.";
        done && tail -f /dev/null;
```

**Comment by wey-gu** [comment]
> ```
>         for i in `seq 1 60`;do
>           var=`nebula-console -addr graphd0 -port 9669 -u root -p nebula -e 'ADD HOSTS "172.28.2.1":9779,"172.28.2.2":9779,"172.28.2.3":9779;'`;
>           if [[ $$? == 0 ]];then
>             break;
>           fi;
>           sleep 1;
>           echo "retry to add hosts.";
>         done && tail -f /dev/null;
> ```

This is better, I'll close this, could you port your implementation here?

**Pull request closed without merging**
