### PR TITLE
Enhance version

### PR DESCRIPTION
**Pull request by HarrisChu**
we could define version environment, and then could launch different version by using if compatible

```
NEBULA_VERSION=v3.0.1 docker-compose up -d
```

### CODE REVIEW

**Comment by HarrisChu** [comment]
BTW
v3 is the latest version for v3.x. i.e. it's same with v3.0.1 now.
maybe we could just create a v3 branch

**Review by wey-gu — APPROVED** [review]
Thanks!
Sorry, I should have done this when you initially mentioned this during our 2.6 branch changes.

**Comment by wey-gu** [comment]
This will significantly simplify the workflow for both maintainer/doc-maintainer and users, if no structure change of the docker- compose file, branch even won't be needed, like you mentioned, branching based on major version will be sufficient

**Comment by HarrisChu** [comment]
hold on

nebula-console is not consistent with nebula. i.e. nebula is v3.0.2 but nebula-console won't release v3.0.2.

**Comment by wey-gu** [comment]
> hold on
> 
> nebula-console is not consistent with nebula. i.e. nebula is v3.0.2 but nebula-console won't release v3.0.2.

how about this, if the variable is with bash compatibility.

```diff
  graphd2:
    image: vesoft/nebula-graphd:${NEBULA_VERSION}
    environment:
      USER: root
      TZ:   "${TZ}"
	@@ -325,7 +325,7 @@ services:
      - SYS_PTRACE
...
  console:
-    image: vesoft/nebula-console:${NEBULA_VERSION}
+    image: vesoft/nebula-console:${NEBULA_VERSION::2}
    entrypoint: ""
    command: 
      - sh
```

```shell
$ export NEBULA_VERSION=v3.0.1
$ echo ${NEBULA_VERSION::2}
v3
```

**Comment by HarrisChu** [comment]
> 

seems it's ok

**Comment by Sophie-Xie** [comment]
It's so long. I'll close it and reopen if necessary.

**Pull request closed without merging**
