### PR TITLE
update image to 2.6.2

### PR DESCRIPTION
**Pull request by wey-gu**

### CODE REVIEW

**Comment by wey-gu** [comment]
This pr will also help docker desktop 4.3.0+ from crashing graphD

**Comment by HarrisChu** [comment]
I think it would be confused, why branch is `2.6.0` and image version is `2.6.2`?

**Comment by wey-gu** [comment]
> 

Sure, should we create a new branch instead?

We may keep it as is to avoid doc change, but in the future, we may only create branches in x.y(3.0) instead of x.y.z(3.0.0) in nebula-docker-compose.

And if we leave it unchanged, in a big chance, new users will use the 2.6.0 image even from the 2.6.2 documentation, when they are running it on 4.3.0 or newer docker desktop(linux VM is cgroupv2 based), graphD will crash as RAM Utils assumed OS are cgroupv1 😭, this will make fresh user down in their first expression.

What do you think, please?

**Comment by wey-gu** [comment]
Created a pr to guide user to find minor versions of images: https://github.com/vesoft-inc/nebula-docker-compose/pull/106

**Comment by HarrisChu** [comment]
prefer 2.6 branch, and declare version variable in .env file, it's the latest nebula version by default.
but we have 2.0.1 branch before, may change a lot

**Comment by wey-gu** [comment]
I will create 2.6 branch later and change all corresponding parts(readme, documentations), later

**Comment by wey-gu** [comment]
@HarrisChu v2.6 is with the same base of v2.6.0 now and the pr was requested to v2.6 now.

I will update the master README after this is merged.

**Comment by wey-gu** [comment]
left the image-v2.6.2 not being deleted as this temp branch was shared to a user for saving him from being crashed during docker desktop 4.3.0+ compose-up...

**Pull request merged**
